import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@mantine/core/styles.css";
import { MantineProvider, MantineThemeOverride } from "@mantine/core";
import { theme as baseTheme } from "@/config/theme";
import { Shell } from "./_components/shell";
import "@mantine/core/styles.layer.css";
import "mantine-datatable/styles.layer.css";
import "@mantine/dates/styles.css";
import "@mantine/carousel/styles.css";
import "@mantine/dropzone/styles.css";
import "@mantine/charts/styles.css";
import Chat from "./_components/chat";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme: Partial<MantineThemeOverride> = baseTheme;

  return (
    <html lang="en">
      <body className={inter.className}>
        <MantineProvider theme={theme}>
          {children}
          {/* <Chat /> */}
        </MantineProvider>
      </body>
    </html>
  );
}
